"use client"
import "./globals.css";
import { useState } from "react";
import { Splide, SplideSlide } from "@splidejs/react-splide";
import "@splidejs/react-splide/css";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const menu = [
    {
      name: "Điện thoại",
      slug: "dtdd",
      item: [
        { slug: "iphone-16e", name: "iPhone16e"},
        { slug: "samsung-s25", name: "Samsung S25"},
        { slug: "oppo-reno13", name: "Oppo Reno 13"}
      ]
    },
    {
      name: "Laptop",
      slug: "laptop",
      item: [
        { slug: "macbook-air-m3", name: "Macbook Air M3" },
        { slug: "asus-zenbook-14", name: "Asus Zenbook 14" },
        { slug: "msi-gaming-thin", name: "MSI Gaming Thin"}
      ]
    },
    {
      name: "Thiết bị âm thanh",
      slug: "tbat",
      item: [
        { slug: "samsung-buds", name: "Samsung Galaxy Buds"},
        { slug: "sony-wh-ch520", name: "Sony WH-CH520"},
        { slug: 'airpod-pro3', name: "AirPods Pro 3"}
      ]
    }
  ]

  return (
    <html lang="en">
      <body className="bg-white text-black min-h-screen">
      <div className="bg-yellow-400 py-4 px-6">
      <Splide
        options={{
          type: "loop",
          perPage: 1,
          perMove: 1,
          gap: "1rem",
          pagination: false,
          arrows: true,
        }}
        aria-label="Menu Carousel"
      >
        {menu.map((cat) => (
          <SplideSlide key={cat.slug}>
            <div className="bg-yellow-300 p-4 rounded-lg shadow flex flex-col gap-2">
              <h3 className="font-bold text-blue-950">{cat.name}</h3>
              <div className="flex flex-col gap-1">
                {cat.item.map((item) => (
                  <Link
                    key={item.slug}
                    href={`/${cat.slug}/${item.slug}`}
                    className="hover:text-amber-950 text-amber-700"
                  >
                    {item.name}
                  </Link>
                ))}
              </div>
            </div>
          </SplideSlide>
        ))}
      </Splide>
      </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
